### ISSUE TITLE
Sources Siret <=> IDCC

### ISSUE THREAD

**Issue by wibimaster** [SocialGouv/siret2idcc#14]
Bonjour !

Félicitations pour ce projet, le résultat est impressionnant :)

Je voulais savoir s'il était possible de connaître la source qui vous permet de construire le fichier de référence `data/WEEZ.csv`, le mapping Siret -> IDCC ; le soucis est sa mise à jour, si nous connaissions l'origine, il serait possible d'aller y jeter un œil pour maintenir par nous même également :)

Merci !

**Comment by revolunet** [comment]
Bonjour,

Ce fichier sera mis à jour régulièrement avec des données fraiches issues de la [DSN](https://fr.wikipedia.org/wiki/D%C3%A9claration_sociale_nominative).  A priori nous n'avons de notre côté aucun moyen de corriger les infos à la source :/

**Comment by wibimaster** [comment]
Mais les APIs DSN ne permettent qu'à chaque entreprise d'avoir les informations sur sa propre entreprise (via authentification), comment peut-on récupérer les infos fraîches d'un SIRET via API ?

J'ai un cas de figure où le SIRET a changé depuis la dernière mise à jour de votre documents, d'où a question :)

**Comment by revolunet** [comment]
Je ne sais pas désolé... notre objectif est de mettre le fichier à jour mensuellement dès que possible

**Comment by revolunet** [comment]
https://github.com/SocialGouv/siret2idcc/pull/16

N'hésitez pas à "watch" le projet pour être informé des MAJ
