### ISSUE TITLE
Update WEEZ.csv

### ISSUE THREAD

**Issue by kevbarns** [SocialGouv/siret2idcc#208]
Bonjour @revolunet, serait-il possible de mettre à jour le csv à partir duquel la relation SIRET -> IDCC est faite ? L'Api nous est vraiment utile côté DINUM - Mission apprentissage - LBA Recruteur. 

Merci d'avance et disponible pour aider au besoin ! 

Kevin
[mail](mailto:kevin.barnoin@beta.gouv.fr)

**Comment by revolunet** [comment]
Bonjour @kevbarns  tu peux retrouver une version à jour et maintenue par la DGT du fichier ici : https://www.data.gouv.fr/fr/datasets/liste-des-conventions-collectives-par-entreprise-siret/

Je te conseille d'utiliser plutôt cette source la

Bien cordialement

**Comment by revolunet** [comment]
Cette API "siret2idcc" est dépréciée en faveur de [recherche-entreprises](https://github.com/SocialGouv/recherche-entreprises), je te conseille de migrer vers cette nouvelle API

**Comment by revolunet** [comment]
l'API a quand été mise à jour avec le dernier fichier via https://github.com/SocialGouv/siret2idcc/pull/209
