### ISSUE TITLE
Delta entre deux fichiers

### ISSUE THREAD

**Issue by mpo-deltacode** [SocialGouv/siret2idcc#210]
Bonjour,
Je rencontre un problème lors de l'import d'un nouveau fichier
Je stock en base de données le fichier Weez et je souhaiterai la mettre à jour lorsqu'un nouveau fichier est disponible
Le problème que je rencontre est que je ne peux pas faire de delta entre l'ancien fichier déja intégré en base et le nouveau fichier, car la valeur "DATE_MAJ" est la même pour tout les résultats, même ceux qui n'ont pas changé. Je dois donc mettre à jour l'intégralité des données, ce qui me cause des timeout ou des limites de perfomances dans la base

Auriez vous une idée de comment réaliser ce delta afin de n'avoir que peu de données à ajouter / mettre a jour ?
(Souhaitant réaliser ce script avec AWS Lambda je ne peux pas faire une fonction qui dure + de 15 minutes)

Merci d'avance à vous

Cordialement

**Comment by revolunet** [comment]
Bonjour,

Les fichiers de données source sont dispos sur data.gouv qui est la référence : https://www.data.gouv.fr/fr/datasets/liste-des-conventions-collectives-par-entreprise-siret vous pouvez y poser votre question

PS : ce projet siret2idcc est déprécié et remplacé par [recherche-entreprises](https://github.com/SocialGouv/recherche-entreprises)

**Comment by revolunet** [comment]
idée : si vous avez toutes les données en base, dans les tables WEEZ1 et WEEZ2 par exemple, vous pourriez faire une query qui extrait les différences

**Comment by mpo-deltacode** [comment]
Merci à vous, nous avons trouvé la solution

Cordialement
